### ISSUE TITLE
[General]Разделить модель/контроллер

### ISSUE THREAD

**Issue by Veleri** [Group2-2/Lab2#17]
Разделить модель/контроллер: все методы касающиеся парсинга и обработки xml - файлов должны находится в модели ( присутствует как в контроллере сервера, так и клиента).
В модели, а именно в методе configuration() присутствует функционал контроллера.

**Comment by Oljk** [comment]
можно пример функционала контроллера в configuration()?

**Comment by Veleri** [comment]
В зависимости от типа команды вы определяете последующие действия приложения - этим должен заниматься контроллер. Контроллер определяет последовательность действий приложения(алгоритм), а модель его выполняет.
