### ISSUE TITLE
[CLIENT]Структура клиента

### ISSUE THREAD

**Issue by Veleri** [Group2-2/Lab2#22]
В структуре клиента вы используете схему: для подключившегося к серверу клиента на стороне клиента создавать отдельный поток. Клиент представляет собой 1 поток подключающийся к серверу, больше быть не может. Эта схема нужна на стороне сервера: для каждого отдельного клиента создавать поток.

**Comment by SviatoslavHavrylo** [comment]
closed

**Comment by SviatoslavHavrylo** [comment]
Fixed #22
