### ISSUE TITLE
[SERVER]Интерфейс сервера

### ISSUE THREAD

**Issue by Veleri** [Group2-2/Lab2#25]
В интерфейс сервера добавить методы для запуска/остановки/перезагрузки сервера. Также подумайте над необходимостью наследования от Runnable именно в интерфейсе ServerController.

**Comment by Oljk** [comment]
Интерфейс ServerController наследуется от  Runnable, или что именно нужно сделать?

**Comment by Oljk** [comment]
https://github.com/Group2-2/Lab2/commit/9036ab8d7acd9333ede48e3643aa39bb84580bfa - и этот коммит, я немного ошиблась в сообщении

**Comment by Veleri** [comment]
Вы наследуете интерфейс от Runnable, но при этом методы Runnable не указываются в самом интерфейсе. Или нужно их добавить в описание или наследоваться от Runnable уже в имплементирующем классе.

**Comment by Oljk** [comment]
вот так?

**Comment by Veleri** [comment]
Да, теперь видно, что по задумке имплиментирующий класс в обязательном порядке должен переопределять данный метод.
