### ISSUE TITLE
[FIX]Кодировка файлов

### ISSUE THREAD

**Issue by Veleri** [Group2-2/Lab2#28]
Поправить кодировку файлов, в которых хранится информация на сервере. Файлы должны быть читаемыми.

**Comment by kudryaA** [comment]
А зачем нам читаемые файли? Наоборот же по-хорошему надо чтобы человек у которого есть доступ к серверу не мог посмотреть информацию о пользователях и читать их сообщения.

**Comment by Veleri** [comment]
Данные настройки зависят от уровня сервера и важности файлов. Данные файлы должны быть в читаемом формате т.к. если пользователь имеет доступ к серверу у него должна быть возможность оперировать данными файлами и вносить, при необходимости изменения.
Что касается безопасности - к файлам настраивается уровень доступа и права.

**Comment by kudryaA** [comment]
Я не понимаю всё равно зачем нужны читаемые файли. Если файли будут читаемые можно будет вносить изменения в сообщения что отправляли пользователи. Даже тех те у кого есть доступ к файлам не должны вносить таких изменений. Так же и в информацию о юзерах и чатах.

**Comment by Veleri** [comment]
Сообщения могут быть зашифрованными, но файлы касающиеся списка пользователей и т.п. в рамках л/р мы делаем в читаемом виде.  Тот формат в котором они находятся сейчас, также не является "безопасным" при желании его легко расшифровать. Повторюсь, что для более серьезных проектов уровень безопасности настраивается или при помощи шифрования необходимых файлов или уровнем доступа. В рамках 2-й л/р - это не требуется. К тому, же администратор должен иметь доступ к таким файлам. И при изменении файлов, проект также должен подхватывать изменения.
