### ISSUE TITLE
[ADD]Удаление неактивных пользователей

### ISSUE THREAD

**Issue by Veleri** [Group2-2/Lab2#9]
Отслеживание "активности" пользователей. Если соединение пользователя не активно, принудительно отсоединять его и убирать из списка онлайн пользователей.

**Comment by Oljk** [comment]
этим занимается метод(отдельный поток) checkOnline() - раз в определенный промежуток времени проходит по всем онлайн-пользователям и проверяет активное ли соединение. Так же, если от пользователя приходит null, тоже идет проверка

**Comment by Veleri** [comment]
Какой промежуток времени установлен? При тестировании "неактивный пользователь" не был удален. Или нужно уменьшить промежуток и удостоверится, что все работает или пойти другим путем реализации.
